name: rss_update

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: blog_feed
      run: python3 rss/gen_blog_feed.py
      
    - uses: stefanzweifel/git-auto-commit-action@v5
